version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "r17x"
    labels:
      - "automerge"
      - "deps-dev"

  - package-ecosystem: npm
    directory: /
    assignees:
      - "grikomsn"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
    labels:
      - "automerge"
      - "dependencies"
