#!/usr/bin/env bash

changes=$(git diff-index --name-only HEAD --)
echo "Checking... modified snapshot.json in @chakra-icons/*"

for maybe_snapshot in $changes 
do
  file_name=$(basename $maybe_snapshot)
  if [ $file_name = "snapshot.json" ]; then
    scope=$(basename $(dirname $maybe_snapshot))
    echo "Found changes in $scope"
    git add $maybe_snapshot
    git commit -m "feat($scope): sync update icons"
    echo "Commited changes in $scope"
  fi
done

echo "Total Snapshot changes:" $(git rev-list --count HEAD ^origin/main)

echo "Clean git stage"

git checkout . 
git clean -fd .

exit 0
