name: Quickstart Setup
description: Setup git user, Node.js, and pnpm cache

runs:
  using: composite
  steps:
    - shell: bash
      run: git config user.email "robot@koding.ninja" && git config user.name "kdnjbot"

    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"

    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
