name: CI

on:
  pull_request:
    branches: [main, beta]
    types: [opened, synchronize]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - uses: wagoid/commitlint-github-action@v5
      - run: |
          type pnpm
          type npm
          echo $PATH
          echo $GITHUB_PATH
          cat $HOME/.bash_profile
          cat $HOME/.bashrc

