name: CI

on: 
  pull_request:
    branches: [main, beta]
    types: [opened, synchronize]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: validate (lint)
        run: |
          yarn lint --no-deps --scope="@chakra-icons/*" --scope="create-*" --parallel 

  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: run test
        run: yarn test 

  build:
    env:
      NODE_OPTIONS: --max_old_space_size=8192
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      
      - name: build project
        run: yarn build
