name: CI

on:
  pull_request:
    branches: [main, beta]
    types: [opened, synchronize]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - run: |
          type pnpm
          type npm
          echo $PATH
          echo $GITHUB_PATH
          cat $HOME/.bash_profile
          cat $HOME/.bashrc

          mkdir -p $GITHUB_WORKSPACE/kdnj/bin

          echo -e '#!/bin/bash\npnpm "$@"' > $GITHUB_WORKSPACE/kdnj/bin/npm && \
            chmod +x $GITHUB_WORKSPACE/kdnj/bin/npm 

          echo "$GITHUB_WORKSPACE/kdnj/bin" >> $GITHUB_PATH

          echo REAL_PATH $PATH
          echo GITHUB_PATH $GITHUB_PATH

          type pnpm
          type npm

          rc=/tmp/rcfile

          echo 'shopt -s expand_aliases' > $rc
          echo 'alias ll="ls -l" ' >> $rc
          echo 'alias npm="$GITHUB_WORKSPACE/kdnj/bin/npm"' >> $rc

          source $rc

          type pnpm
          type npm

          npm version

          npm --help
