name: Release

on:
  push:
    branches: [main, beta]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - run: pnpm --filter="@chakra-icons/*" --filter="create-*" run lint

  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - run: pnpm run test

  build:
    env:
      NODE_OPTIONS: --max_old_space_size=8192
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - run: pnpm run build

  release:
    needs: [validate, test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - env:
          NODE_OPTIONS: --max_old_space_size=8192
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: "kdnjbot"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: "robot@koding.ninja"
          GIT_COMMITTER_EMAIL: "robot@koding.ninja"
          GIT_AUTHOR_NAME: "@kdnjbot"
          GIT_COMMITTER_NAME: "@kdnjbot"
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        run: |
          # PATCH: replace workspace:* to *
          # multi-semantic-release (especially @semrel-extra/npm not supported version `workspace:*`.
          # So, need to replace it before release
          homebin=$HOME/kdnj/bin
          mkdir -p $homebin
          echo -e '#!/bin/bash\npnpm "$@"' > $homebin/npm && chmod +x $homebin/npm

          rc=/tmp/rcfile
          echo 'shopt -s expand_aliases' > $rc
          echo 'alias npm="$homebin/npm"' >> $rc
          source $rc
          find . -type f -name "package.json" -not -path './node_modules*' -not -path './.git*' -exec sed -i 's/workspace:\*/\*/g' {} \;
          npm --help
          pnpm run release
