name: Release

on:
  push:
    branches: [main, beta]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - run: pnpm --filter="@chakra-icons/*" --filter="create-*" run lint

  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - run: pnpm run test

  build:
    env:
      NODE_OPTIONS: --max_old_space_size=8192
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - run: pnpm run build

  release:
    needs: [validate, test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/quickstart
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: "kdnjbot"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: "robot@koding.ninja"
          GIT_COMMITTER_EMAIL: "robot@koding.ninja"
          GIT_AUTHOR_NAME: "@kdnjbot"
          GIT_COMMITTER_NAME: "@kdnjbot"
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        run: pnpm run release
