name: Sync

on:
  schedule:
    # run job every week on sunday at 23:59 PM
    - cron: 59 23 * * 0

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: ./.github/actions/quickstart
      - run: pnpm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - run: ./.github/scripts/sync-snapshot
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: "sync-icons"
          author: "kdnjbot <robot@koding.ninja>"
          committer: "kdnjbot <robot@koding.ninja>"
